version: '3.1'
services:
    app:
        container_name: docker-spring-boot
        image: docker-spring-boot
        build: ./
        ports:
          - "8080:8080"
        depends_on:
          - db
          - rabbitmq
        environment:
           SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medication_project
           SPRING_RABBITMQ_HOST: rabbitmq


    db:
      image: postgres
      container_name: db
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=alkaalka
        - POSTGRES_USER=postgres
        - POSTGRES_DB=medication_project

    rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"